---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-added-large-files
      - id: detect-private-key
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.2
    hooks:
      - id: uv-lock
  - repo: https://github.com/frontierhq/pre-commit-hooks
    rev: v0.0.1
    hooks:
      - id: make-test
